# Displays
.equ SECOND_UNIT_DISPLAY 288
.equ SECOND_TEN_DISPLAY  289
.equ MINUTE_UNIT_DISPLAY 290
.equ MINUTE_TEN_DISPLAY  291
.equ HOUR_UNIT_DISPLAY   292
.equ HOUR_TEN_DISPLAY    293

# Temporizador
.equ READ_TIME            384
.equ SET_TIMER_TO_SECONDS 385
.equ SET_TIMER_TO_FAST    386

.equ CLEAR_TIME           447

.equ SECONDS 10
.equ MINUTES 12
.equ HOURS   13

START:
    # STORE @SET_TIMER_TO_SECONDS

    LOADI R0, 0
    STORE R0, SECOND_UNIT_DISPLAY
    STORE R0, SECOND_TEN_DISPLAY
    STORE R0, MINUTE_UNIT_DISPLAY
    STORE R0, MINUTE_TEN_DISPLAY
    STORE R0, HOUR_UNIT_DISPLAY
    STORE R0, HOUR_TEN_DISPLAY

    STORE @CLEAR_TIME
    
LOOP:
    LOAD @READ_TIME
    ANDI $1
    CEQI $0
    JEQ @LOOP

    STORE @CLEAR_TIME
    JSR @INCREMENT_TIME

    JSR @WRITE_TIME

    JMP @LOOP

INCREMENT_TIME:
    LOAD @SECONDS
    ADDI $1
    STORE @SECONDS

    CEQI $10
    JEQ @RESET_SECONDS

    RET

RESET_SECONDS:
    LOADI R0, 0
    STORE @SECONDS

    LOAD @MINUTES
    ADDI $1
    STORE MINUTES

    CEQI $10
    JEQ @RESET_MINUTES

    RET

RESET_MINUTES:
    LOADI R0, 0
    STORE @MINUTES

    LOAD HOURS
    ADDI $1
    STORE HOURS

    CEQI $24
    JEQ @RESET_HOURS

    RET

RESET_HOURS:
    STORE $0, HOURS
    RET

WRITE_TIME:
    LOAD @SECONDS
    STORE @SECOND_UNIT_DISPLAY

    LOAD @MINUTES
    STORE @MINUTE_UNIT_DISPLAY

    LOAD @HOURS
    STORE @HOUR_UNIT_DISPLAY

    RET